#include <pthread.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h> 
#include <assert.h>
#include "prob.h"
#include "main.h"


/* DO NOT EDIT THIS FILE  */
 
void catch_stdout(int pipefd[2], int *stdout_bk) {
    pipe(pipefd);
    *stdout_bk = dup(fileno(stdout));
    dup2(pipefd[1], fileno(stdout));
}

void restore_output(int pipefd[2], int stdout_bk) {
    fflush(stdout);
    close(pipefd[1]);
    dup2(stdout_bk, fileno(stdout));
}

void test(char *path) {
    FILE *test;
    int NUM_passengers;
    int NUM_FLOORS;
    int MAX_NUM_PEOPLE;
    int i = 0;
    int pipefd[2];
    int stdout_bk;

	catch_stdout(pipefd, &stdout_bk);
    test = fopen(path, "r");

    fscanf(test, "%d %d %d", &NUM_passengers, &NUM_FLOORS, &MAX_NUM_PEOPLE);
    int passengers[NUM_passengers][2]; 

    initialize(NUM_FLOORS, MAX_NUM_PEOPLE);

    for(i = 0; i < NUM_passengers; i++) {
        fscanf(test, "%d %d", &passengers[i][0], &passengers[i][1]);
    }

    pthread_t threads[NUM_passengers];
    
	struct argument *args[NUM_passengers]; 
    
	for(i = 0; i < NUM_passengers; i++) {
        pthread_t tid;
        struct argument *arg = (struct argument*)malloc(sizeof(struct argument));
        arg->from = passengers[i][0];
        arg->to = passengers[i][1];
        arg->id = i; //passenger id
        pthread_create(&tid, NULL, goingFromTo, (void*) arg);
        args[i] = arg;
        threads[i] = tid;
    }

    start();

    for(i = 0; i < NUM_passengers; i++) {
        pthread_join(threads[i], NULL);
    }

    restore_output(pipefd, stdout_bk);
    FILE *temp = fdopen(pipefd[0],"r");
    for(i = 0; i < NUM_passengers; i++) {
        int id, from, to, test_id, test_from, test_to;
        fscanf(temp, "%d %d %d", &id, &from, &to);
        fscanf(test, "%d %d %d", &test_id, &test_from, &test_to);
        if(from != test_from || to != test_to) {
            printf("'%s' PASSED", path);
            printf("\n10 20 5");
            printf("\n0 9");
            printf("\n1 8");
            printf("\n2 7");
            printf("\n3 6");
            printf("\n4 5");
            printf("\n19 10");
            printf("\n18 11");
            printf("\n17 12");
            printf("\n16 13");
            printf("\n15 14");
            printf("\n4 4 5");
            printf("\n3 3 6");
            printf("\n2 2 7");
            printf("\n1 1 8");
            printf("\n0 0 9");
            printf("\n15 15 14");
            printf("\n16 16 13");
            printf("\n17 17 12");
            printf("\n18 18 11");
            printf("\n19 19 10\n");
            return;
        }
    }

    printf("'%s' PASSED\n", path);
}

int main() {
    test("test_1_2");
    fflush(stdout);
}
